// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.support-attachment@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SUPPORT_ATTACHMENT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SUPPORT_ATTACHMENT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_support_attachment { () => { "{\"capability_id\":\"lenso.support-attachment@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"attach_content\",\"get_attachment\",\"list_attachments\",\"upload_and_attach\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_support_attachment_client { () => { "{\"capability_id\":\"lenso.support-attachment@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_support_attachment_client { () => { "{\"capability_id\":\"lenso.support-attachment@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" }; }

pub const ATTACH_CONTENT_OPERATION: &str = "attach_content";
pub const GET_ATTACHMENT_OPERATION: &str = "get_attachment";
pub const LIST_ATTACHMENTS_OPERATION: &str = "list_attachments";
pub const UPLOAD_AND_ATTACH_OPERATION: &str = "upload_and_attach";

pub use lenso_contract_runtime::{Bytes, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AttachContentRequest {
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "content_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_id: String,
    #[serde(rename = "filename")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub filename: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: MediaType,
    #[serde(rename = "message_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message_id: Option<String>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: SourceOwner,
    #[serde(rename = "visibility")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub visibility: Visibility,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum MediaType {
    #[serde(rename = "image/png")]
    ImagePng,
    #[serde(rename = "image/jpeg")]
    ImageJpeg,
    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SourceOwner {
    #[serde(rename = "resource_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_id: String,
    #[serde(rename = "resource_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_type: String,
    #[serde(rename = "revision_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum Visibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AttachContentResponse {
    #[serde(rename = "attachment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attachment: Attachment,
    #[serde(rename = "receipt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipt_id: String,
    #[serde(rename = "replayed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub replayed: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Attachment {
    #[serde(rename = "attached_by_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attached_by_subject: String,
    #[serde(rename = "attachment_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attachment_id: String,
    #[serde(rename = "case_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_id: String,
    #[serde(rename = "content_created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_created_at: Timestamp,
    #[serde(rename = "content_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "filename")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub filename: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: AttachmentMediaType,
    #[serde(rename = "message_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message_id: Option<String>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "sha256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sha256: String,
    #[serde(rename = "size_bytes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub size_bytes: i64,
    #[serde(rename = "visibility")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub visibility: AttachmentVisibility,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AttachmentMediaType {
    #[serde(rename = "image/png")]
    ImagePng,
    #[serde(rename = "image/jpeg")]
    ImageJpeg,
    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AttachmentVisibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AttachContentError {
    ContentMismatch,
    ContentNotFound,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetAttachmentRequest {
    #[serde(rename = "attachment_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attachment_id: String,
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetAttachmentResponse {
    #[serde(rename = "attachment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attachment: Attachment,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetAttachmentError {
    AttachmentNotFound,
    Forbidden,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListAttachmentsRequest {
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "message_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message_id: Option<String>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListAttachmentsResponse {
    #[serde(rename = "attachments")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attachments: Vec<Attachment>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListAttachmentsError {
    Forbidden,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UploadAndAttachRequest {
    #[serde(rename = "case_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub case_ref: String,
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: Bytes,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_type: UploadContentType,
    #[serde(rename = "filename")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub filename: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "message_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message_id: Option<String>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "visibility")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub visibility: Visibility,
}

impl fmt::Debug for UploadAndAttachRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("UploadAndAttachRequest")
            .field("case_ref", &self.case_ref)
            .field("content", &"<redacted>")
            .field("content_type", &self.content_type)
            .field("filename", &self.filename)
            .field("idempotency_key", &self.idempotency_key)
            .field("message_id", &self.message_id)
            .field("organization_id", &self.organization_id)
            .field("visibility", &self.visibility)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum UploadContentType {
    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UploadAndAttachResponse {
    #[serde(rename = "attachment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attachment: Attachment,
    #[serde(rename = "receipt_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipt_id: String,
    #[serde(rename = "replayed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub replayed: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UploadAndAttachError {
    ContentRejected,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct SupportAttachmentAttachContent;
impl RequestCapability for SupportAttachmentAttachContent {
    type Request = AttachContentRequest;
    type Response = AttachContentResponse;
    type DomainError = AttachContentError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ATTACH_CONTENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportAttachmentRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).attach_content(context, request)
    }
}

#[derive(Debug)]
pub struct SupportAttachmentGetAttachment;
impl RequestCapability for SupportAttachmentGetAttachment {
    type Request = GetAttachmentRequest;
    type Response = GetAttachmentResponse;
    type DomainError = GetAttachmentError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_ATTACHMENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportAttachmentRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_attachment(context, request)
    }
}

#[derive(Debug)]
pub struct SupportAttachmentListAttachments;
impl RequestCapability for SupportAttachmentListAttachments {
    type Request = ListAttachmentsRequest;
    type Response = ListAttachmentsResponse;
    type DomainError = ListAttachmentsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_ATTACHMENTS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportAttachmentRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_attachments(context, request)
    }
}

#[derive(Debug)]
pub struct SupportAttachmentUploadAndAttach;
impl RequestCapability for SupportAttachmentUploadAndAttach {
    type Request = UploadAndAttachRequest;
    type Response = UploadAndAttachResponse;
    type DomainError = UploadAndAttachError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != UPLOAD_AND_ATTACH_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SupportAttachmentRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).upload_and_attach(context, request)
    }
}

impl serde::Serialize for AttachContentError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContentMismatch => serializer.serialize_str("content_mismatch"),
            Self::ContentNotFound => serializer.serialize_str("content_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AttachContentError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "content_mismatch" => Ok(Self::ContentMismatch),
                "content_not_found" => Ok(Self::ContentNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetAttachmentError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AttachmentNotFound => serializer.serialize_str("attachment_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetAttachmentError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "attachment_not_found" => Ok(Self::AttachmentNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListAttachmentsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListAttachmentsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for UploadAndAttachError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContentRejected => serializer.serialize_str("content_rejected"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for UploadAndAttachError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "content_rejected" => Ok(Self::ContentRejected),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_attach_content_request(value: &AttachContentRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_attach_content_request(wire: &str) -> Result<AttachContentRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_attach_content_response(value: &AttachContentResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_attach_content_response(wire: &str) -> Result<AttachContentResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_attach_content_error(value: &AttachContentError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_attach_content_error(wire: &str) -> Result<AttachContentError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_attachment_request(value: &GetAttachmentRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_attachment_request(wire: &str) -> Result<GetAttachmentRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_attachment_response(value: &GetAttachmentResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_attachment_response(wire: &str) -> Result<GetAttachmentResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_attachment_error(value: &GetAttachmentError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_attachment_error(wire: &str) -> Result<GetAttachmentError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_attachments_request(value: &ListAttachmentsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_attachments_request(wire: &str) -> Result<ListAttachmentsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_attachments_response(value: &ListAttachmentsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_attachments_response(wire: &str) -> Result<ListAttachmentsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_attachments_error(value: &ListAttachmentsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_attachments_error(wire: &str) -> Result<ListAttachmentsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_upload_and_attach_request(value: &UploadAndAttachRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upload_and_attach_request(wire: &str) -> Result<UploadAndAttachRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_upload_and_attach_response(value: &UploadAndAttachResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upload_and_attach_response(wire: &str) -> Result<UploadAndAttachResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_upload_and_attach_error(value: &UploadAndAttachError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upload_and_attach_error(wire: &str) -> Result<UploadAndAttachError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSupportAttachmentAttachContentResult {
    fn __lenso_into_result(self) -> Result<Result<AttachContentResponse, AttachContentError>, RuntimeFailure>;
}
impl __LensoIntoSupportAttachmentAttachContentResult for Result<AttachContentResponse, AttachContentError> {
    fn __lenso_into_result(self) -> Result<Result<AttachContentResponse, AttachContentError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportAttachmentAttachContentResult for Result<Result<AttachContentResponse, AttachContentError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AttachContentResponse, AttachContentError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportAttachmentAttachContentResult for Result<AttachContentResponse, lenso_plugin_authoring::PluginError<AttachContentError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AttachContentResponse, AttachContentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportAttachmentAttachContentResult for Result<AttachContentResponse, SupportAttachmentAttachContentInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AttachContentResponse, AttachContentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportAttachmentAttachContentInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportAttachmentAttachContentInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSupportAttachmentGetAttachmentResult {
    fn __lenso_into_result(self) -> Result<Result<GetAttachmentResponse, GetAttachmentError>, RuntimeFailure>;
}
impl __LensoIntoSupportAttachmentGetAttachmentResult for Result<GetAttachmentResponse, GetAttachmentError> {
    fn __lenso_into_result(self) -> Result<Result<GetAttachmentResponse, GetAttachmentError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportAttachmentGetAttachmentResult for Result<Result<GetAttachmentResponse, GetAttachmentError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetAttachmentResponse, GetAttachmentError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportAttachmentGetAttachmentResult for Result<GetAttachmentResponse, lenso_plugin_authoring::PluginError<GetAttachmentError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetAttachmentResponse, GetAttachmentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportAttachmentGetAttachmentResult for Result<GetAttachmentResponse, SupportAttachmentGetAttachmentInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetAttachmentResponse, GetAttachmentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportAttachmentGetAttachmentInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportAttachmentGetAttachmentInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSupportAttachmentListAttachmentsResult {
    fn __lenso_into_result(self) -> Result<Result<ListAttachmentsResponse, ListAttachmentsError>, RuntimeFailure>;
}
impl __LensoIntoSupportAttachmentListAttachmentsResult for Result<ListAttachmentsResponse, ListAttachmentsError> {
    fn __lenso_into_result(self) -> Result<Result<ListAttachmentsResponse, ListAttachmentsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportAttachmentListAttachmentsResult for Result<Result<ListAttachmentsResponse, ListAttachmentsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListAttachmentsResponse, ListAttachmentsError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportAttachmentListAttachmentsResult for Result<ListAttachmentsResponse, lenso_plugin_authoring::PluginError<ListAttachmentsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListAttachmentsResponse, ListAttachmentsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportAttachmentListAttachmentsResult for Result<ListAttachmentsResponse, SupportAttachmentListAttachmentsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListAttachmentsResponse, ListAttachmentsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportAttachmentListAttachmentsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportAttachmentListAttachmentsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoSupportAttachmentUploadAndAttachResult {
    fn __lenso_into_result(self) -> Result<Result<UploadAndAttachResponse, UploadAndAttachError>, RuntimeFailure>;
}
impl __LensoIntoSupportAttachmentUploadAndAttachResult for Result<UploadAndAttachResponse, UploadAndAttachError> {
    fn __lenso_into_result(self) -> Result<Result<UploadAndAttachResponse, UploadAndAttachError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSupportAttachmentUploadAndAttachResult for Result<Result<UploadAndAttachResponse, UploadAndAttachError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<UploadAndAttachResponse, UploadAndAttachError>, RuntimeFailure> { self }
}
impl __LensoIntoSupportAttachmentUploadAndAttachResult for Result<UploadAndAttachResponse, lenso_plugin_authoring::PluginError<UploadAndAttachError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<UploadAndAttachResponse, UploadAndAttachError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSupportAttachmentUploadAndAttachResult for Result<UploadAndAttachResponse, SupportAttachmentUploadAndAttachInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<UploadAndAttachResponse, UploadAndAttachError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SupportAttachmentUploadAndAttachInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SupportAttachmentUploadAndAttachInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SupportAttachmentProvider: fmt::Debug + 'static {
    fn attach_content(&self, context: InvocationContext, request: AttachContentRequest) -> NativeRequestFuture<SupportAttachmentAttachContent>;
    fn get_attachment(&self, context: InvocationContext, request: GetAttachmentRequest) -> NativeRequestFuture<SupportAttachmentGetAttachment>;
    fn list_attachments(&self, context: InvocationContext, request: ListAttachmentsRequest) -> NativeRequestFuture<SupportAttachmentListAttachments>;
    fn upload_and_attach(&self, context: InvocationContext, request: UploadAndAttachRequest) -> NativeRequestFuture<SupportAttachmentUploadAndAttach>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_support_attachment {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSupportAttachment;
        impl $crate::SupportAttachmentProvider for $plugin {
        fn attach_content(&self, context: __LensoNativeSupportSupportAttachment::InvocationContext, request: $crate::AttachContentRequest) -> __LensoNativeSupportSupportAttachment::NativeRequestFuture<$crate::SupportAttachmentAttachContent> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::attach_content(&plugin, context, request).await;
                $crate::__LensoIntoSupportAttachmentAttachContentResult::__lenso_into_result(result)
            })
        }
        fn get_attachment(&self, context: __LensoNativeSupportSupportAttachment::InvocationContext, request: $crate::GetAttachmentRequest) -> __LensoNativeSupportSupportAttachment::NativeRequestFuture<$crate::SupportAttachmentGetAttachment> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_attachment(&plugin, context, request).await;
                $crate::__LensoIntoSupportAttachmentGetAttachmentResult::__lenso_into_result(result)
            })
        }
        fn list_attachments(&self, context: __LensoNativeSupportSupportAttachment::InvocationContext, request: $crate::ListAttachmentsRequest) -> __LensoNativeSupportSupportAttachment::NativeRequestFuture<$crate::SupportAttachmentListAttachments> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_attachments(&plugin, context, request).await;
                $crate::__LensoIntoSupportAttachmentListAttachmentsResult::__lenso_into_result(result)
            })
        }
        fn upload_and_attach(&self, context: __LensoNativeSupportSupportAttachment::InvocationContext, request: $crate::UploadAndAttachRequest) -> __LensoNativeSupportSupportAttachment::NativeRequestFuture<$crate::SupportAttachmentUploadAndAttach> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::upload_and_attach(&plugin, context, request).await;
                $crate::__LensoIntoSupportAttachmentUploadAndAttachResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct SupportAttachmentRequestEndpoint { provider: Rc<dyn SupportAttachmentProvider> }

#[derive(Debug)]
pub struct SupportAttachmentEndpoint<P: SupportAttachmentProvider> { provider: Rc<P>, request_endpoint: SupportAttachmentRequestEndpoint }
impl<P: SupportAttachmentProvider> SupportAttachmentEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SupportAttachmentProvider> = provider.clone();
        Self { provider, request_endpoint: SupportAttachmentRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SupportAttachmentProvider> NativeRequestEndpoint for SupportAttachmentEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ATTACH_CONTENT_OPERATION,
        GET_ATTACHMENT_OPERATION,
        LIST_ATTACHMENTS_OPERATION,
        UPLOAD_AND_ATTACH_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ATTACH_CONTENT_OPERATION => {
                let Ok(request) = request.downcast::<AttachContentRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).attach_content(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_ATTACHMENT_OPERATION => {
                let Ok(request) = request.downcast::<GetAttachmentRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_attachment(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_ATTACHMENTS_OPERATION => {
                let Ok(request) = request.downcast::<ListAttachmentsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_attachments(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            UPLOAD_AND_ATTACH_OPERATION => {
                let Ok(request) = request.downcast::<UploadAndAttachRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).upload_and_attach(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_support_attachment {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SupportAttachmentEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_support_attachment {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_support_attachment!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SupportAttachmentClient {
    attach_content: NativeRequestHandle<SupportAttachmentAttachContent>,
    get_attachment: NativeRequestHandle<SupportAttachmentGetAttachment>,
    list_attachments: NativeRequestHandle<SupportAttachmentListAttachments>,
    upload_and_attach: NativeRequestHandle<SupportAttachmentUploadAndAttach>,
}
impl SupportAttachmentClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn attach_content(&self, request: AttachContentRequest) -> Result<AttachContentResponse, SupportAttachmentAttachContentInvocationError> {
        self.attach_content.invoke(ATTACH_CONTENT_OPERATION, request).await
            .map_err(SupportAttachmentAttachContentInvocationError::Runtime)?
            .map_err(SupportAttachmentAttachContentInvocationError::Domain)
    }

    pub async fn attach_content_with_context(&self, context: InvocationContext, request: AttachContentRequest) -> Result<AttachContentResponse, SupportAttachmentAttachContentInvocationError> {
        self.attach_content.invoke_with_context(ATTACH_CONTENT_OPERATION, context, request).await
            .map_err(SupportAttachmentAttachContentInvocationError::Runtime)?
            .map_err(SupportAttachmentAttachContentInvocationError::Domain)
    }

    pub async fn get_attachment(&self, request: GetAttachmentRequest) -> Result<GetAttachmentResponse, SupportAttachmentGetAttachmentInvocationError> {
        self.get_attachment.invoke(GET_ATTACHMENT_OPERATION, request).await
            .map_err(SupportAttachmentGetAttachmentInvocationError::Runtime)?
            .map_err(SupportAttachmentGetAttachmentInvocationError::Domain)
    }

    pub async fn get_attachment_with_context(&self, context: InvocationContext, request: GetAttachmentRequest) -> Result<GetAttachmentResponse, SupportAttachmentGetAttachmentInvocationError> {
        self.get_attachment.invoke_with_context(GET_ATTACHMENT_OPERATION, context, request).await
            .map_err(SupportAttachmentGetAttachmentInvocationError::Runtime)?
            .map_err(SupportAttachmentGetAttachmentInvocationError::Domain)
    }

    pub async fn list_attachments(&self, request: ListAttachmentsRequest) -> Result<ListAttachmentsResponse, SupportAttachmentListAttachmentsInvocationError> {
        self.list_attachments.invoke(LIST_ATTACHMENTS_OPERATION, request).await
            .map_err(SupportAttachmentListAttachmentsInvocationError::Runtime)?
            .map_err(SupportAttachmentListAttachmentsInvocationError::Domain)
    }

    pub async fn list_attachments_with_context(&self, context: InvocationContext, request: ListAttachmentsRequest) -> Result<ListAttachmentsResponse, SupportAttachmentListAttachmentsInvocationError> {
        self.list_attachments.invoke_with_context(LIST_ATTACHMENTS_OPERATION, context, request).await
            .map_err(SupportAttachmentListAttachmentsInvocationError::Runtime)?
            .map_err(SupportAttachmentListAttachmentsInvocationError::Domain)
    }

    pub async fn upload_and_attach(&self, request: UploadAndAttachRequest) -> Result<UploadAndAttachResponse, SupportAttachmentUploadAndAttachInvocationError> {
        self.upload_and_attach.invoke(UPLOAD_AND_ATTACH_OPERATION, request).await
            .map_err(SupportAttachmentUploadAndAttachInvocationError::Runtime)?
            .map_err(SupportAttachmentUploadAndAttachInvocationError::Domain)
    }

    pub async fn upload_and_attach_with_context(&self, context: InvocationContext, request: UploadAndAttachRequest) -> Result<UploadAndAttachResponse, SupportAttachmentUploadAndAttachInvocationError> {
        self.upload_and_attach.invoke_with_context(UPLOAD_AND_ATTACH_OPERATION, context, request).await
            .map_err(SupportAttachmentUploadAndAttachInvocationError::Runtime)?
            .map_err(SupportAttachmentUploadAndAttachInvocationError::Domain)
    }
}

impl CapabilityClient for SupportAttachmentClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            attach_content: dependencies.one::<SupportAttachmentAttachContent>()?,
            get_attachment: dependencies.one::<SupportAttachmentGetAttachment>()?,
            list_attachments: dependencies.one::<SupportAttachmentListAttachments>()?,
            upload_and_attach: dependencies.one::<SupportAttachmentUploadAndAttach>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SupportAttachmentClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    attach_content: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportAttachmentAttachContent>()?,
                    get_attachment: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportAttachmentGetAttachment>()?,
                    list_attachments: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportAttachmentListAttachments>()?,
                    upload_and_attach: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<SupportAttachmentUploadAndAttach>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SupportAttachmentAttachContentInvocationError {
    Domain(AttachContentError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SupportAttachmentGetAttachmentInvocationError {
    Domain(GetAttachmentError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SupportAttachmentListAttachmentsInvocationError {
    Domain(ListAttachmentsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SupportAttachmentUploadAndAttachInvocationError {
    Domain(UploadAndAttachError),
    Runtime(RuntimeFailure),
}
